// <auto-generated>
/*
 * Automation API
 *
 * The Automation API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = BeamAutomationClient.Client.ClientUtils;
using BeamAutomationClient.Client;

namespace BeamAutomationClient.Model
{
    /// <summary>
    /// GetAssetListingsResponseV2DataInnerPrice
    /// </summary>
    public partial class GetAssetListingsResponseV2DataInnerPrice : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAssetListingsResponseV2DataInnerPrice" /> class.
        /// </summary>
        /// <param name="amount">amount</param>
        /// <param name="currency">currency</param>
        /// <param name="netAmount">netAmount</param>
        [JsonConstructor]
        public GetAssetListingsResponseV2DataInnerPrice(Option<GetAssetListingsResponseV2DataInnerPriceAmount?> amount = default, Option<GetAssetListingsResponseV2DataInnerPriceCurrency?> currency = default, Option<GetAssetListingsResponseV2DataInnerPriceAmount?> netAmount = default)
        {
            AmountOption = amount;
            CurrencyOption = currency;
            NetAmountOption = netAmount;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GetAssetListingsResponseV2DataInnerPriceAmount?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public GetAssetListingsResponseV2DataInnerPriceAmount? Amount { get { return this. AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Currency
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GetAssetListingsResponseV2DataInnerPriceCurrency?> CurrencyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [JsonPropertyName("currency")]
        public GetAssetListingsResponseV2DataInnerPriceCurrency? Currency { get { return this. CurrencyOption; } set { this.CurrencyOption = new(value); } }

        /// <summary>
        /// Used to track the state of NetAmount
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<GetAssetListingsResponseV2DataInnerPriceAmount?> NetAmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets NetAmount
        /// </summary>
        [JsonPropertyName("netAmount")]
        public GetAssetListingsResponseV2DataInnerPriceAmount? NetAmount { get { return this. NetAmountOption; } set { this.NetAmountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAssetListingsResponseV2DataInnerPrice {\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  NetAmount: ").Append(NetAmount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetAssetListingsResponseV2DataInnerPrice" />
    /// </summary>
    public class GetAssetListingsResponseV2DataInnerPriceJsonConverter : JsonConverter<GetAssetListingsResponseV2DataInnerPrice>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetAssetListingsResponseV2DataInnerPrice" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetAssetListingsResponseV2DataInnerPrice Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<GetAssetListingsResponseV2DataInnerPriceAmount?> amount = default;
            Option<GetAssetListingsResponseV2DataInnerPriceCurrency?> currency = default;
            Option<GetAssetListingsResponseV2DataInnerPriceAmount?> netAmount = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "amount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                amount = new Option<GetAssetListingsResponseV2DataInnerPriceAmount?>(JsonSerializer.Deserialize<GetAssetListingsResponseV2DataInnerPriceAmount>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "currency":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                currency = new Option<GetAssetListingsResponseV2DataInnerPriceCurrency?>(JsonSerializer.Deserialize<GetAssetListingsResponseV2DataInnerPriceCurrency>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "netAmount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                netAmount = new Option<GetAssetListingsResponseV2DataInnerPriceAmount?>(JsonSerializer.Deserialize<GetAssetListingsResponseV2DataInnerPriceAmount>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            return new GetAssetListingsResponseV2DataInnerPrice(amount, currency, netAmount);
        }

        /// <summary>
        /// Serializes a <see cref="GetAssetListingsResponseV2DataInnerPrice" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getAssetListingsResponseV2DataInnerPrice"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetAssetListingsResponseV2DataInnerPrice getAssetListingsResponseV2DataInnerPrice, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, getAssetListingsResponseV2DataInnerPrice, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetAssetListingsResponseV2DataInnerPrice" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getAssetListingsResponseV2DataInnerPrice"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, GetAssetListingsResponseV2DataInnerPrice getAssetListingsResponseV2DataInnerPrice, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getAssetListingsResponseV2DataInnerPrice.AmountOption.IsSet)
                if (getAssetListingsResponseV2DataInnerPrice.AmountOption.Value != null)
                {
                    writer.WritePropertyName("amount");
                    JsonSerializer.Serialize(writer, getAssetListingsResponseV2DataInnerPrice.Amount, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("amount");
            if (getAssetListingsResponseV2DataInnerPrice.CurrencyOption.IsSet)
                if (getAssetListingsResponseV2DataInnerPrice.CurrencyOption.Value != null)
                {
                    writer.WritePropertyName("currency");
                    JsonSerializer.Serialize(writer, getAssetListingsResponseV2DataInnerPrice.Currency, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("currency");
            if (getAssetListingsResponseV2DataInnerPrice.NetAmountOption.IsSet)
                if (getAssetListingsResponseV2DataInnerPrice.NetAmountOption.Value != null)
                {
                    writer.WritePropertyName("netAmount");
                    JsonSerializer.Serialize(writer, getAssetListingsResponseV2DataInnerPrice.NetAmount, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("netAmount");
        }
    }
}