// <auto-generated>
/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = BeamAutomationClient.Client.ClientUtils;
using BeamAutomationClient.Client;

namespace BeamAutomationClient.Model
{
    /// <summary>
    /// GetChainResponse
    /// </summary>
    public partial class GetChainResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetChainResponse" /> class.
        /// </summary>
        /// <param name="blockNumber">blockNumber</param>
        /// <param name="chainId">chainId</param>
        /// <param name="nativeCurrency">nativeCurrency</param>
        [JsonConstructor]
        public GetChainResponse(decimal blockNumber, decimal chainId, GetChainResponseNativeCurrency nativeCurrency)
        {
            BlockNumber = blockNumber;
            ChainId = chainId;
            NativeCurrency = nativeCurrency;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets BlockNumber
        /// </summary>
        [JsonPropertyName("blockNumber")]
        public decimal BlockNumber { get; set; }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [JsonPropertyName("chainId")]
        public decimal ChainId { get; set; }

        /// <summary>
        /// Gets or Sets NativeCurrency
        /// </summary>
        [JsonPropertyName("nativeCurrency")]
        public GetChainResponseNativeCurrency NativeCurrency { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetChainResponse {\n");
            sb.Append("  BlockNumber: ").Append(BlockNumber).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  NativeCurrency: ").Append(NativeCurrency).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetChainResponse" />
    /// </summary>
    public class GetChainResponseJsonConverter : JsonConverter<GetChainResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetChainResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetChainResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<decimal?> blockNumber = default;
            Option<decimal?> chainId = default;
            Option<GetChainResponseNativeCurrency?> nativeCurrency = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "blockNumber":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                blockNumber = new Option<decimal?>(utf8JsonReader.GetDecimal());
                            break;
                        case "chainId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                chainId = new Option<decimal?>(utf8JsonReader.GetDecimal());
                            break;
                        case "nativeCurrency":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                nativeCurrency = new Option<GetChainResponseNativeCurrency?>(JsonSerializer.Deserialize<GetChainResponseNativeCurrency>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!blockNumber.IsSet)
                throw new ArgumentException("Property is required for class GetChainResponse.", nameof(blockNumber));

            if (!chainId.IsSet)
                throw new ArgumentException("Property is required for class GetChainResponse.", nameof(chainId));

            if (!nativeCurrency.IsSet)
                throw new ArgumentException("Property is required for class GetChainResponse.", nameof(nativeCurrency));

            if (blockNumber.IsSet && blockNumber.Value == null)
                throw new ArgumentNullException(nameof(blockNumber), "Property is not nullable for class GetChainResponse.");

            if (chainId.IsSet && chainId.Value == null)
                throw new ArgumentNullException(nameof(chainId), "Property is not nullable for class GetChainResponse.");

            if (nativeCurrency.IsSet && nativeCurrency.Value == null)
                throw new ArgumentNullException(nameof(nativeCurrency), "Property is not nullable for class GetChainResponse.");

            return new GetChainResponse(blockNumber.Value!.Value!, chainId.Value!.Value!, nativeCurrency.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GetChainResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getChainResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetChainResponse getChainResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, getChainResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetChainResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getChainResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, GetChainResponse getChainResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getChainResponse.NativeCurrency == null)
                throw new ArgumentNullException(nameof(getChainResponse.NativeCurrency), "Property is required for class GetChainResponse.");

            writer.WriteNumber("blockNumber", getChainResponse.BlockNumber);

            writer.WriteNumber("chainId", getChainResponse.ChainId);

            writer.WritePropertyName("nativeCurrency");
            JsonSerializer.Serialize(writer, getChainResponse.NativeCurrency, jsonSerializerOptions);
        }
    }
}