// <auto-generated>
/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using BeamPlayerClient.Client;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// PlayerGetOnRampQuoteResponseQuote
    /// </summary>
    public partial class PlayerGetOnRampQuoteResponseQuote : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerGetOnRampQuoteResponseQuote" /> class.
        /// </summary>
        /// <param name="input">input</param>
        /// <param name="output">output</param>
        [JsonConstructor]
        public PlayerGetOnRampQuoteResponseQuote(PlayerGetOnRampQuoteResponseQuoteInput input, PlayerGetOnRampQuoteResponseQuoteOutput output)
        {
            Input = input;
            Output = output;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Input
        /// </summary>
        [JsonPropertyName("input")]
        public PlayerGetOnRampQuoteResponseQuoteInput Input { get; set; }

        /// <summary>
        /// Gets or Sets Output
        /// </summary>
        [JsonPropertyName("output")]
        public PlayerGetOnRampQuoteResponseQuoteOutput Output { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerGetOnRampQuoteResponseQuote {\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("  Output: ").Append(Output).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlayerGetOnRampQuoteResponseQuote" />
    /// </summary>
    public class PlayerGetOnRampQuoteResponseQuoteJsonConverter : JsonConverter<PlayerGetOnRampQuoteResponseQuote>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlayerGetOnRampQuoteResponseQuote" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlayerGetOnRampQuoteResponseQuote Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PlayerGetOnRampQuoteResponseQuoteInput> input = default;
            Option<PlayerGetOnRampQuoteResponseQuoteOutput> output = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "input":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                input = new Option<PlayerGetOnRampQuoteResponseQuoteInput>(JsonSerializer.Deserialize<PlayerGetOnRampQuoteResponseQuoteInput>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "output":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                output = new Option<PlayerGetOnRampQuoteResponseQuoteOutput>(JsonSerializer.Deserialize<PlayerGetOnRampQuoteResponseQuoteOutput>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!input.IsSet)
                throw new ArgumentException("Property is required for class PlayerGetOnRampQuoteResponseQuote.", nameof(input));

            if (!output.IsSet)
                throw new ArgumentException("Property is required for class PlayerGetOnRampQuoteResponseQuote.", nameof(output));

            if (input.IsSet && input.Value == null)
                throw new ArgumentNullException(nameof(input), "Property is not nullable for class PlayerGetOnRampQuoteResponseQuote.");

            if (output.IsSet && output.Value == null)
                throw new ArgumentNullException(nameof(output), "Property is not nullable for class PlayerGetOnRampQuoteResponseQuote.");

            return new PlayerGetOnRampQuoteResponseQuote(input.Value, output.Value);
        }

        /// <summary>
        /// Serializes a <see cref="PlayerGetOnRampQuoteResponseQuote" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playerGetOnRampQuoteResponseQuote"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlayerGetOnRampQuoteResponseQuote playerGetOnRampQuoteResponseQuote, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, playerGetOnRampQuoteResponseQuote, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlayerGetOnRampQuoteResponseQuote" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playerGetOnRampQuoteResponseQuote"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlayerGetOnRampQuoteResponseQuote playerGetOnRampQuoteResponseQuote, JsonSerializerOptions jsonSerializerOptions)
        {
            if (playerGetOnRampQuoteResponseQuote.Input == null)
                throw new ArgumentNullException(nameof(playerGetOnRampQuoteResponseQuote.Input), "Property is required for class PlayerGetOnRampQuoteResponseQuote.");

            if (playerGetOnRampQuoteResponseQuote.Output == null)
                throw new ArgumentNullException(nameof(playerGetOnRampQuoteResponseQuote.Output), "Property is required for class PlayerGetOnRampQuoteResponseQuote.");

            writer.WritePropertyName("input");
            JsonSerializer.Serialize(writer, playerGetOnRampQuoteResponseQuote.Input, jsonSerializerOptions);
            writer.WritePropertyName("output");
            JsonSerializer.Serialize(writer, playerGetOnRampQuoteResponseQuote.Output, jsonSerializerOptions);
        }
    }
}