// <auto-generated>
/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = BeamPlayerClient.Client.ClientUtils;
using BeamPlayerClient.Client;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// PlayerCommonOperationResponseActionsInner
    /// </summary>
    public partial class PlayerCommonOperationResponseActionsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerCommonOperationResponseActionsInner" /> class.
        /// </summary>
        /// <param name="context">context</param>
        /// <param name="id">id</param>
        /// <param name="index">index</param>
        /// <param name="transaction">transaction</param>
        /// <param name="type">type</param>
        /// <param name="operationId">operationId</param>
        /// <param name="signature">signature</param>
        [JsonConstructor]
        public PlayerCommonOperationResponseActionsInner(Object context, string id, int index, PlayerCommonOperationResponseActionsInnerAllOfOneOfTransaction transaction, TypeEnum type, string? operationId = default, OneOf? signature = default)
        {
            Context = context;
            Id = id;
            Index = index;
            Transaction = transaction;
            Type = type;
            OperationId = operationId;
            Signature = signature;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        [JsonConverter(typeof(TypeEnumJsonConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum Sign for value: Sign
            /// </summary>
            Sign = 1
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("Sign"))
                return TypeEnum.Sign;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("Sign"))
                return TypeEnum.Sign;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.Sign)
                return "Sign";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Converts <see cref="TypeEnum"/> to and from the JSON value
        /// </summary>
        public static class TypeEnumValueConverter
        {
            /// <summary>
            /// Parses a given value to <see cref="TypeEnum"/>
            /// </summary>
            /// <param name="value"></param>
            /// <returns></returns>
            public static TypeEnum FromString(string value)
            {
                    if (value.Equals("Sign"))
                        return TypeEnum.Sign;

                throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
            }

            /// <summary>
            /// Parses a given value to <see cref="TypeEnum"/>
            /// </summary>
            /// <param name="value"></param>
            /// <returns></returns>
            public static TypeEnum? FromStringOrDefault(string value)
            {
                    if (value.Equals("Sign"))
                        return TypeEnum.Sign;

                return null;
            }

            /// <summary>
            /// Converts the <see cref="TypeEnum"/> to the json value
            /// </summary>
            /// <param name="value"></param>
            /// <returns></returns>
            /// <exception cref="NotImplementedException"></exception>
            public static string ToJsonValue(TypeEnum value)
            {
                        if (value == TypeEnum.Sign)
                            return "Sign";

                throw new NotImplementedException($"Value could not be handled: '{value}'");
            }
        }

        /// <summary>
        /// A Json converter for type <see cref="TypeEnum"/>
        /// </summary>
        /// <exception cref="NotImplementedException"></exception>
        public class TypeEnumJsonConverter : JsonConverter<TypeEnum>
        {
            /// <summary>
            /// Returns a TypeEnum from the Json object
            /// </summary>
            /// <param name="reader"></param>
            /// <param name="typeToConvert"></param>
            /// <param name="options"></param>
            /// <returns></returns>
            public override TypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
            {
                string? rawValue = reader.GetString();

                TypeEnum? result = rawValue == null
                    ? null
                    : TypeEnumValueConverter.FromStringOrDefault(rawValue);

                if (result != null)
                    return result.Value;

                throw new JsonException();
            }

            /// <summary>
            /// Writes the TypeEnum to the json writer
            /// </summary>
            /// <param name="writer"></param>
            /// <param name="typeEnum"></param>
            /// <param name="options"></param>
            public override void Write(Utf8JsonWriter writer, TypeEnum typeEnum, JsonSerializerOptions options)
            {
                writer.WriteStringValue(TypeEnumValueConverter.ToJsonValue(typeEnum));
            }
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Context
        /// </summary>
        [JsonPropertyName("context")]
        public Object Context { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Index
        /// </summary>
        [JsonPropertyName("index")]
        public int Index { get; set; }

        /// <summary>
        /// Gets or Sets Transaction
        /// </summary>
        [JsonPropertyName("transaction")]
        public PlayerCommonOperationResponseActionsInnerAllOfOneOfTransaction Transaction { get; set; }

        /// <summary>
        /// Gets or Sets OperationId
        /// </summary>
        [JsonPropertyName("operationId")]
        public string? OperationId { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [JsonPropertyName("signature")]
        public OneOf? Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerCommonOperationResponseActionsInner {\n");
            sb.Append("  Context: ").Append(Context).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Index: ").Append(Index).Append("\n");
            sb.Append("  Transaction: ").Append(Transaction).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  OperationId: ").Append(OperationId).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlayerCommonOperationResponseActionsInner" />
    /// </summary>
    public class PlayerCommonOperationResponseActionsInnerJsonConverter : JsonConverter<PlayerCommonOperationResponseActionsInner>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlayerCommonOperationResponseActionsInner" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlayerCommonOperationResponseActionsInner Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Object?> context = default;
            Option<string?> id = default;
            Option<int?> index = default;
            Option<PlayerCommonOperationResponseActionsInnerAllOfOneOfTransaction?> transaction = default;
            Option<PlayerCommonOperationResponseActionsInner.TypeEnum?> type = default;
            Option<string?> operationId = default;
            Option<OneOf?> signature = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "context":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                context = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "index":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                index = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "transaction":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                transaction = new Option<PlayerCommonOperationResponseActionsInnerAllOfOneOfTransaction?>(JsonSerializer.Deserialize<PlayerCommonOperationResponseActionsInnerAllOfOneOfTransaction>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "type":
                            string? typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<PlayerCommonOperationResponseActionsInner.TypeEnum?>(PlayerCommonOperationResponseActionsInner.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "operationId":
                            operationId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "signature":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                signature = new Option<OneOf?>(JsonSerializer.Deserialize<OneOf>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!context.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(context));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(id));

            if (!index.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(index));

            if (!transaction.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(transaction));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(type));

            if (!operationId.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(operationId));

            if (!signature.IsSet)
                throw new ArgumentException("Property is required for class PlayerCommonOperationResponseActionsInner.", nameof(signature));

            if (context.IsSet && context.Value == null)
                throw new ArgumentNullException(nameof(context), "Property is not nullable for class PlayerCommonOperationResponseActionsInner.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class PlayerCommonOperationResponseActionsInner.");

            if (index.IsSet && index.Value == null)
                throw new ArgumentNullException(nameof(index), "Property is not nullable for class PlayerCommonOperationResponseActionsInner.");

            if (transaction.IsSet && transaction.Value == null)
                throw new ArgumentNullException(nameof(transaction), "Property is not nullable for class PlayerCommonOperationResponseActionsInner.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class PlayerCommonOperationResponseActionsInner.");

            return new PlayerCommonOperationResponseActionsInner(context.Value!, id.Value!, index.Value!.Value!, transaction.Value!, type.Value!.Value!, operationId.Value!, signature.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="PlayerCommonOperationResponseActionsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playerCommonOperationResponseActionsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlayerCommonOperationResponseActionsInner playerCommonOperationResponseActionsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, playerCommonOperationResponseActionsInner, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlayerCommonOperationResponseActionsInner" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playerCommonOperationResponseActionsInner"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, PlayerCommonOperationResponseActionsInner playerCommonOperationResponseActionsInner, JsonSerializerOptions jsonSerializerOptions)
        {
            if (playerCommonOperationResponseActionsInner.Context == null)
                throw new ArgumentNullException(nameof(playerCommonOperationResponseActionsInner.Context), "Property is required for class PlayerCommonOperationResponseActionsInner.");

            if (playerCommonOperationResponseActionsInner.Id == null)
                throw new ArgumentNullException(nameof(playerCommonOperationResponseActionsInner.Id), "Property is required for class PlayerCommonOperationResponseActionsInner.");

            if (playerCommonOperationResponseActionsInner.Transaction == null)
                throw new ArgumentNullException(nameof(playerCommonOperationResponseActionsInner.Transaction), "Property is required for class PlayerCommonOperationResponseActionsInner.");

            writer.WritePropertyName("context");
            JsonSerializer.Serialize(writer, playerCommonOperationResponseActionsInner.Context, jsonSerializerOptions);
            writer.WriteString("id", playerCommonOperationResponseActionsInner.Id);

            writer.WriteNumber("index", playerCommonOperationResponseActionsInner.Index);

            writer.WritePropertyName("transaction");
            JsonSerializer.Serialize(writer, playerCommonOperationResponseActionsInner.Transaction, jsonSerializerOptions);
            var typeRawValue = PlayerCommonOperationResponseActionsInner.TypeEnumToJsonValue(playerCommonOperationResponseActionsInner.Type);
            writer.WriteString("type", typeRawValue);
            if (playerCommonOperationResponseActionsInner.OperationId != null)
                writer.WriteString("operationId", playerCommonOperationResponseActionsInner.OperationId);
            else
                writer.WriteNull("operationId");

            if (playerCommonOperationResponseActionsInner.Signature != null)
            {
                writer.WritePropertyName("signature");
                JsonSerializer.Serialize(writer, playerCommonOperationResponseActionsInner.Signature, jsonSerializerOptions);
            }
            else
                writer.WriteNull("signature");
        }
    }
}