// <auto-generated>
/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIClientUtils = BeamPlayerClient.Client.ClientUtils;
using BeamPlayerClient.Client;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction
    /// </summary>
    public partial class PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction" /> class.
        /// </summary>
        /// <param name="sponsored">sponsored</param>
        /// <param name="openfortId">openfortId</param>
        [JsonConstructor]
        public PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction(bool sponsored, Option<string?> openfortId = default)
        {
            Sponsored = sponsored;
            OpenfortIdOption = openfortId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Sponsored
        /// </summary>
        [JsonPropertyName("sponsored")]
        public bool Sponsored { get; set; }

        /// <summary>
        /// Used to track the state of OpenfortId
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OpenfortIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OpenfortId
        /// </summary>
        [JsonPropertyName("openfortId")]
        public string? OpenfortId { get { return this. OpenfortIdOption; } set { this.OpenfortIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction {\n");
            sb.Append("  Sponsored: ").Append(Sponsored).Append("\n");
            sb.Append("  OpenfortId: ").Append(OpenfortId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction" />
    /// </summary>
    public class PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransactionJsonConverter : JsonConverter<PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> sponsored = default;
            Option<string?> openfortId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "sponsored":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                sponsored = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "openfortId":
                            openfortId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!sponsored.IsSet)
                throw new ArgumentException("Property is required for class PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction.", nameof(sponsored));

            if (sponsored.IsSet && sponsored.Value == null)
                throw new ArgumentNullException(nameof(sponsored), "Property is not nullable for class PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction.");

            return new PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction(sponsored.Value!.Value!, openfortId);
        }

        /// <summary>
        /// Serializes a <see cref="PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, PlayerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("sponsored", playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction.Sponsored);

            if (playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction.OpenfortIdOption.IsSet)
                if (playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction.OpenfortIdOption.Value != null)
                    writer.WriteString("openfortId", playerCreateOperationRequestInputActionsInnerAllOfOneOfTransaction.OpenfortId);
                else
                    writer.WriteNull("openfortId");
        }
    }
}