// <auto-generated>
/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Beam.Client;

namespace Beam.Model
{
    /// <summary>
    /// AddContractResponse
    /// </summary>
    public partial class AddContractResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddContractResponse" /> class.
        /// </summary>
        /// <param name="address">address</param>
        /// <param name="chainId">chainId</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="externalId">externalId</param>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="gameId">gameId</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public AddContractResponse(string address, int chainId, DateTime createdAt, string externalId, string id, TypeEnum type, DateTime updatedAt, string gameId = default, string name = default)
        {
            Address = address;
            ChainId = chainId;
            CreatedAt = createdAt;
            ExternalId = externalId;
            Id = id;
            Type = type;
            UpdatedAt = updatedAt;
            GameId = gameId;
            Name = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Type
        /// </summary>
        public enum TypeEnum
        {
            /// <summary>
            /// Enum ERC20 for value: ERC20
            /// </summary>
            ERC20 = 1,

            /// <summary>
            /// Enum ERC721 for value: ERC721
            /// </summary>
            ERC721 = 2,

            /// <summary>
            /// Enum ERC1155 for value: ERC1155
            /// </summary>
            ERC1155 = 3,

            /// <summary>
            /// Enum SEAPORT for value: SEAPORT
            /// </summary>
            SEAPORT = 4,

            /// <summary>
            /// Enum UNISWAPV2 for value: UNISWAPV2
            /// </summary>
            UNISWAPV2 = 5,

            /// <summary>
            /// Enum WETH for value: WETH
            /// </summary>
            WETH = 6
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static TypeEnum TypeEnumFromString(string value)
        {
            if (value.Equals("ERC20"))
                return TypeEnum.ERC20;

            if (value.Equals("ERC721"))
                return TypeEnum.ERC721;

            if (value.Equals("ERC1155"))
                return TypeEnum.ERC1155;

            if (value.Equals("SEAPORT"))
                return TypeEnum.SEAPORT;

            if (value.Equals("UNISWAPV2"))
                return TypeEnum.UNISWAPV2;

            if (value.Equals("WETH"))
                return TypeEnum.WETH;

            throw new NotImplementedException($"Could not convert value to type TypeEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="TypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static TypeEnum? TypeEnumFromStringOrDefault(string value)
        {
            if (value.Equals("ERC20"))
                return TypeEnum.ERC20;

            if (value.Equals("ERC721"))
                return TypeEnum.ERC721;

            if (value.Equals("ERC1155"))
                return TypeEnum.ERC1155;

            if (value.Equals("SEAPORT"))
                return TypeEnum.SEAPORT;

            if (value.Equals("UNISWAPV2"))
                return TypeEnum.UNISWAPV2;

            if (value.Equals("WETH"))
                return TypeEnum.WETH;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="TypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string TypeEnumToJsonValue(TypeEnum value)
        {
            if (value == TypeEnum.ERC20)
                return "ERC20";

            if (value == TypeEnum.ERC721)
                return "ERC721";

            if (value == TypeEnum.ERC1155)
                return "ERC1155";

            if (value == TypeEnum.SEAPORT)
                return "SEAPORT";

            if (value == TypeEnum.UNISWAPV2)
                return "UNISWAPV2";

            if (value == TypeEnum.WETH)
                return "WETH";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [JsonPropertyName("address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [JsonPropertyName("chainId")]
        public int ChainId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets GameId
        /// </summary>
        [JsonPropertyName("gameId")]
        public string GameId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddContractResponse {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  GameId: ").Append(GameId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AddContractResponse" />
    /// </summary>
    public class AddContractResponseJsonConverter : JsonConverter<AddContractResponse>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize UpdatedAt
        /// </summary>
        public static string UpdatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="AddContractResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AddContractResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> address = default;
            Option<int?> chainId = default;
            Option<DateTime?> createdAt = default;
            Option<string> externalId = default;
            Option<string> id = default;
            Option<AddContractResponse.TypeEnum?> type = default;
            Option<DateTime?> updatedAt = default;
            Option<string> gameId = default;
            Option<string> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "address":
                            address = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "chainId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                chainId = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "createdAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "externalId":
                            externalId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "id":
                            id = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "type":
                            string typeRawValue = utf8JsonReader.GetString();
                            if (typeRawValue != null)
                                type = new Option<AddContractResponse.TypeEnum?>(AddContractResponse.TypeEnumFromStringOrDefault(typeRawValue));
                            break;
                        case "updatedAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                updatedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "gameId":
                            gameId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!address.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(address));

            if (!chainId.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(chainId));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(createdAt));

            if (!externalId.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(externalId));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(id));

            if (!type.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(type));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(updatedAt));

            if (!gameId.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(gameId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class AddContractResponse.", nameof(name));

            if (address.IsSet && address.Value == null)
                throw new ArgumentNullException(nameof(address), "Property is not nullable for class AddContractResponse.");

            if (chainId.IsSet && chainId.Value == null)
                throw new ArgumentNullException(nameof(chainId), "Property is not nullable for class AddContractResponse.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class AddContractResponse.");

            if (externalId.IsSet && externalId.Value == null)
                throw new ArgumentNullException(nameof(externalId), "Property is not nullable for class AddContractResponse.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class AddContractResponse.");

            if (type.IsSet && type.Value == null)
                throw new ArgumentNullException(nameof(type), "Property is not nullable for class AddContractResponse.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class AddContractResponse.");

            return new AddContractResponse(address.Value, chainId.Value.Value, createdAt.Value.Value, externalId.Value, id.Value, type.Value.Value, updatedAt.Value.Value, gameId.Value, name.Value);
        }

        /// <summary>
        /// Serializes a <see cref="AddContractResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addContractResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AddContractResponse addContractResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, addContractResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AddContractResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="addContractResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, AddContractResponse addContractResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (addContractResponse.Address == null)
                throw new ArgumentNullException(nameof(addContractResponse.Address), "Property is required for class AddContractResponse.");

            if (addContractResponse.ExternalId == null)
                throw new ArgumentNullException(nameof(addContractResponse.ExternalId), "Property is required for class AddContractResponse.");

            if (addContractResponse.Id == null)
                throw new ArgumentNullException(nameof(addContractResponse.Id), "Property is required for class AddContractResponse.");

            writer.WriteString("address", addContractResponse.Address);

            writer.WriteNumber("chainId", addContractResponse.ChainId);

            writer.WriteString("createdAt", addContractResponse.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("externalId", addContractResponse.ExternalId);

            writer.WriteString("id", addContractResponse.Id);

            var typeRawValue = AddContractResponse.TypeEnumToJsonValue(addContractResponse.Type);
            writer.WriteString("type", typeRawValue);
            writer.WriteString("updatedAt", addContractResponse.UpdatedAt.ToString(UpdatedAtFormat));

            if (addContractResponse.GameId != null)
                writer.WriteString("gameId", addContractResponse.GameId);
            else
                writer.WriteNull("gameId");

            if (addContractResponse.Name != null)
                writer.WriteString("name", addContractResponse.Name);
            else
                writer.WriteNull("name");
        }
    }
}
