// <auto-generated>
/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Beam.Client;

namespace Beam.Model
{
    /// <summary>
    /// CreateProfileResponse
    /// </summary>
    public partial class CreateProfileResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProfileResponse" /> class.
        /// </summary>
        /// <param name="externalEntityId">externalEntityId</param>
        /// <param name="externalId">externalId</param>
        /// <param name="gameId">gameId</param>
        /// <param name="id">id</param>
        /// <param name="wallets">wallets</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="userConnectionCreatedAt">userConnectionCreatedAt</param>
        /// <param name="userId">userId</param>
        [JsonConstructor]
        public CreateProfileResponse(string externalEntityId, string externalId, string gameId, string id, List<CreateProfileResponseWalletsInner> wallets, Object createdAt = default, Object updatedAt = default, Object userConnectionCreatedAt = default, string userId = default)
        {
            ExternalEntityId = externalEntityId;
            ExternalId = externalId;
            GameId = gameId;
            Id = id;
            Wallets = wallets;
            CreatedAt = createdAt;
            UpdatedAt = updatedAt;
            UserConnectionCreatedAt = userConnectionCreatedAt;
            UserId = userId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ExternalEntityId
        /// </summary>
        [JsonPropertyName("externalEntityId")]
        public string ExternalEntityId { get; set; }

        /// <summary>
        /// Gets or Sets ExternalId
        /// </summary>
        [JsonPropertyName("externalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// Gets or Sets GameId
        /// </summary>
        [JsonPropertyName("gameId")]
        public string GameId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Wallets
        /// </summary>
        [JsonPropertyName("wallets")]
        public List<CreateProfileResponseWalletsInner> Wallets { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("createdAt")]
        public Object CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updatedAt")]
        public Object UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UserConnectionCreatedAt
        /// </summary>
        [JsonPropertyName("userConnectionCreatedAt")]
        public Object UserConnectionCreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("userId")]
        public string UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateProfileResponse {\n");
            sb.Append("  ExternalEntityId: ").Append(ExternalEntityId).Append("\n");
            sb.Append("  ExternalId: ").Append(ExternalId).Append("\n");
            sb.Append("  GameId: ").Append(GameId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Wallets: ").Append(Wallets).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  UserConnectionCreatedAt: ").Append(UserConnectionCreatedAt).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateProfileResponse" />
    /// </summary>
    public class CreateProfileResponseJsonConverter : JsonConverter<CreateProfileResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateProfileResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateProfileResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> externalEntityId = default;
            Option<string> externalId = default;
            Option<string> gameId = default;
            Option<string> id = default;
            Option<List<CreateProfileResponseWalletsInner>> wallets = default;
            Option<Object> createdAt = default;
            Option<Object> updatedAt = default;
            Option<Object> userConnectionCreatedAt = default;
            Option<string> userId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "externalEntityId":
                            externalEntityId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "externalId":
                            externalId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "gameId":
                            gameId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "id":
                            id = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "wallets":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                wallets = new Option<List<CreateProfileResponseWalletsInner>>(JsonSerializer.Deserialize<List<CreateProfileResponseWalletsInner>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "createdAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                createdAt = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "updatedAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                updatedAt = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "userConnectionCreatedAt":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                userConnectionCreatedAt = new Option<Object>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "userId":
                            userId = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!externalEntityId.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(externalEntityId));

            if (!externalId.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(externalId));

            if (!gameId.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(gameId));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(id));

            if (!wallets.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(wallets));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(createdAt));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(updatedAt));

            if (!userConnectionCreatedAt.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(userConnectionCreatedAt));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class CreateProfileResponse.", nameof(userId));

            if (externalEntityId.IsSet && externalEntityId.Value == null)
                throw new ArgumentNullException(nameof(externalEntityId), "Property is not nullable for class CreateProfileResponse.");

            if (externalId.IsSet && externalId.Value == null)
                throw new ArgumentNullException(nameof(externalId), "Property is not nullable for class CreateProfileResponse.");

            if (gameId.IsSet && gameId.Value == null)
                throw new ArgumentNullException(nameof(gameId), "Property is not nullable for class CreateProfileResponse.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class CreateProfileResponse.");

            if (wallets.IsSet && wallets.Value == null)
                throw new ArgumentNullException(nameof(wallets), "Property is not nullable for class CreateProfileResponse.");

            return new CreateProfileResponse(externalEntityId.Value, externalId.Value, gameId.Value, id.Value, wallets.Value, createdAt.Value, updatedAt.Value, userConnectionCreatedAt.Value, userId.Value);
        }

        /// <summary>
        /// Serializes a <see cref="CreateProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateProfileResponse createProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, createProfileResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateProfileResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createProfileResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, CreateProfileResponse createProfileResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createProfileResponse.ExternalEntityId == null)
                throw new ArgumentNullException(nameof(createProfileResponse.ExternalEntityId), "Property is required for class CreateProfileResponse.");

            if (createProfileResponse.ExternalId == null)
                throw new ArgumentNullException(nameof(createProfileResponse.ExternalId), "Property is required for class CreateProfileResponse.");

            if (createProfileResponse.GameId == null)
                throw new ArgumentNullException(nameof(createProfileResponse.GameId), "Property is required for class CreateProfileResponse.");

            if (createProfileResponse.Id == null)
                throw new ArgumentNullException(nameof(createProfileResponse.Id), "Property is required for class CreateProfileResponse.");

            if (createProfileResponse.Wallets == null)
                throw new ArgumentNullException(nameof(createProfileResponse.Wallets), "Property is required for class CreateProfileResponse.");

            writer.WriteString("externalEntityId", createProfileResponse.ExternalEntityId);

            writer.WriteString("externalId", createProfileResponse.ExternalId);

            writer.WriteString("gameId", createProfileResponse.GameId);

            writer.WriteString("id", createProfileResponse.Id);

            writer.WritePropertyName("wallets");
            JsonSerializer.Serialize(writer, createProfileResponse.Wallets, jsonSerializerOptions);
            if (createProfileResponse.CreatedAt != null)
            {
                writer.WritePropertyName("createdAt");
                JsonSerializer.Serialize(writer, createProfileResponse.CreatedAt, jsonSerializerOptions);
            }
            else
                writer.WriteNull("createdAt");
            if (createProfileResponse.UpdatedAt != null)
            {
                writer.WritePropertyName("updatedAt");
                JsonSerializer.Serialize(writer, createProfileResponse.UpdatedAt, jsonSerializerOptions);
            }
            else
                writer.WriteNull("updatedAt");
            if (createProfileResponse.UserConnectionCreatedAt != null)
            {
                writer.WritePropertyName("userConnectionCreatedAt");
                JsonSerializer.Serialize(writer, createProfileResponse.UserConnectionCreatedAt, jsonSerializerOptions);
            }
            else
                writer.WriteNull("userConnectionCreatedAt");
            if (createProfileResponse.UserId != null)
                writer.WriteString("userId", createProfileResponse.UserId);
            else
                writer.WriteNull("userId");
        }
    }
}
