// <auto-generated>
/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Beam.Client;

namespace Beam.Model
{
    /// <summary>
    /// GetAssetResponseOwnershipByAddressesInnerUserProfile
    /// </summary>
    public partial class GetAssetResponseOwnershipByAddressesInnerUserProfile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAssetResponseOwnershipByAddressesInnerUserProfile" /> class.
        /// </summary>
        /// <param name="isVerified">isVerified</param>
        /// <param name="bio">bio</param>
        /// <param name="profilePicture">profilePicture</param>
        /// <param name="profilePictureUrl">profilePictureUrl</param>
        /// <param name="telegram">telegram</param>
        /// <param name="twitter">twitter</param>
        /// <param name="website">website</param>
        [JsonConstructor]
        public GetAssetResponseOwnershipByAddressesInnerUserProfile(bool isVerified, Option<string> bio = default, Option<string> profilePicture = default, Option<string> profilePictureUrl = default, Option<string> telegram = default, Option<string> twitter = default, Option<string> website = default)
        {
            IsVerified = isVerified;
            BioOption = bio;
            ProfilePictureOption = profilePicture;
            ProfilePictureUrlOption = profilePictureUrl;
            TelegramOption = telegram;
            TwitterOption = twitter;
            WebsiteOption = website;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets IsVerified
        /// </summary>
        [JsonPropertyName("isVerified")]
        public bool IsVerified { get; set; }

        /// <summary>
        /// Used to track the state of Bio
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> BioOption { get; private set; }

        /// <summary>
        /// Gets or Sets Bio
        /// </summary>
        [JsonPropertyName("bio")]
        public string Bio { get { return this. BioOption; } set { this.BioOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProfilePicture
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ProfilePictureOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProfilePicture
        /// </summary>
        [JsonPropertyName("profilePicture")]
        public string ProfilePicture { get { return this. ProfilePictureOption; } set { this.ProfilePictureOption = new(value); } }

        /// <summary>
        /// Used to track the state of ProfilePictureUrl
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ProfilePictureUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets ProfilePictureUrl
        /// </summary>
        [JsonPropertyName("profilePictureUrl")]
        public string ProfilePictureUrl { get { return this. ProfilePictureUrlOption; } set { this.ProfilePictureUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of Telegram
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TelegramOption { get; private set; }

        /// <summary>
        /// Gets or Sets Telegram
        /// </summary>
        [JsonPropertyName("telegram")]
        public string Telegram { get { return this. TelegramOption; } set { this.TelegramOption = new(value); } }

        /// <summary>
        /// Used to track the state of Twitter
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TwitterOption { get; private set; }

        /// <summary>
        /// Gets or Sets Twitter
        /// </summary>
        [JsonPropertyName("twitter")]
        public string Twitter { get { return this. TwitterOption; } set { this.TwitterOption = new(value); } }

        /// <summary>
        /// Used to track the state of Website
        /// </summary>
        [JsonIgnore]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> WebsiteOption { get; private set; }

        /// <summary>
        /// Gets or Sets Website
        /// </summary>
        [JsonPropertyName("website")]
        public string Website { get { return this. WebsiteOption; } set { this.WebsiteOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAssetResponseOwnershipByAddressesInnerUserProfile {\n");
            sb.Append("  IsVerified: ").Append(IsVerified).Append("\n");
            sb.Append("  Bio: ").Append(Bio).Append("\n");
            sb.Append("  ProfilePicture: ").Append(ProfilePicture).Append("\n");
            sb.Append("  ProfilePictureUrl: ").Append(ProfilePictureUrl).Append("\n");
            sb.Append("  Telegram: ").Append(Telegram).Append("\n");
            sb.Append("  Twitter: ").Append(Twitter).Append("\n");
            sb.Append("  Website: ").Append(Website).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetAssetResponseOwnershipByAddressesInnerUserProfile" />
    /// </summary>
    public class GetAssetResponseOwnershipByAddressesInnerUserProfileJsonConverter : JsonConverter<GetAssetResponseOwnershipByAddressesInnerUserProfile>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetAssetResponseOwnershipByAddressesInnerUserProfile" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetAssetResponseOwnershipByAddressesInnerUserProfile Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isVerified = default;
            Option<string> bio = default;
            Option<string> profilePicture = default;
            Option<string> profilePictureUrl = default;
            Option<string> telegram = default;
            Option<string> twitter = default;
            Option<string> website = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "isVerified":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isVerified = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "bio":
                            bio = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "profilePicture":
                            profilePicture = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "profilePictureUrl":
                            profilePictureUrl = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "telegram":
                            telegram = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "twitter":
                            twitter = new Option<string>(utf8JsonReader.GetString());
                            break;
                        case "website":
                            website = new Option<string>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!isVerified.IsSet)
                throw new ArgumentException("Property is required for class GetAssetResponseOwnershipByAddressesInnerUserProfile.", nameof(isVerified));

            if (isVerified.IsSet && isVerified.Value == null)
                throw new ArgumentNullException(nameof(isVerified), "Property is not nullable for class GetAssetResponseOwnershipByAddressesInnerUserProfile.");

            return new GetAssetResponseOwnershipByAddressesInnerUserProfile(isVerified.Value.Value, bio, profilePicture, profilePictureUrl, telegram, twitter, website);
        }

        /// <summary>
        /// Serializes a <see cref="GetAssetResponseOwnershipByAddressesInnerUserProfile" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getAssetResponseOwnershipByAddressesInnerUserProfile"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetAssetResponseOwnershipByAddressesInnerUserProfile getAssetResponseOwnershipByAddressesInnerUserProfile, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(ref writer, getAssetResponseOwnershipByAddressesInnerUserProfile, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetAssetResponseOwnershipByAddressesInnerUserProfile" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getAssetResponseOwnershipByAddressesInnerUserProfile"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(ref Utf8JsonWriter writer, GetAssetResponseOwnershipByAddressesInnerUserProfile getAssetResponseOwnershipByAddressesInnerUserProfile, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteBoolean("isVerified", getAssetResponseOwnershipByAddressesInnerUserProfile.IsVerified);

            if (getAssetResponseOwnershipByAddressesInnerUserProfile.BioOption.IsSet)
                if (getAssetResponseOwnershipByAddressesInnerUserProfile.BioOption.Value != null)
                    writer.WriteString("bio", getAssetResponseOwnershipByAddressesInnerUserProfile.Bio);
                else
                    writer.WriteNull("bio");

            if (getAssetResponseOwnershipByAddressesInnerUserProfile.ProfilePictureOption.IsSet)
                if (getAssetResponseOwnershipByAddressesInnerUserProfile.ProfilePictureOption.Value != null)
                    writer.WriteString("profilePicture", getAssetResponseOwnershipByAddressesInnerUserProfile.ProfilePicture);
                else
                    writer.WriteNull("profilePicture");

            if (getAssetResponseOwnershipByAddressesInnerUserProfile.ProfilePictureUrlOption.IsSet)
                if (getAssetResponseOwnershipByAddressesInnerUserProfile.ProfilePictureUrlOption.Value != null)
                    writer.WriteString("profilePictureUrl", getAssetResponseOwnershipByAddressesInnerUserProfile.ProfilePictureUrl);
                else
                    writer.WriteNull("profilePictureUrl");

            if (getAssetResponseOwnershipByAddressesInnerUserProfile.TelegramOption.IsSet)
                if (getAssetResponseOwnershipByAddressesInnerUserProfile.TelegramOption.Value != null)
                    writer.WriteString("telegram", getAssetResponseOwnershipByAddressesInnerUserProfile.Telegram);
                else
                    writer.WriteNull("telegram");

            if (getAssetResponseOwnershipByAddressesInnerUserProfile.TwitterOption.IsSet)
                if (getAssetResponseOwnershipByAddressesInnerUserProfile.TwitterOption.Value != null)
                    writer.WriteString("twitter", getAssetResponseOwnershipByAddressesInnerUserProfile.Twitter);
                else
                    writer.WriteNull("twitter");

            if (getAssetResponseOwnershipByAddressesInnerUserProfile.WebsiteOption.IsSet)
                if (getAssetResponseOwnershipByAddressesInnerUserProfile.WebsiteOption.Value != null)
                    writer.WriteString("website", getAssetResponseOwnershipByAddressesInnerUserProfile.Website);
                else
                    writer.WriteNull("website");
        }
    }
}
