/*
 * Beam game development API
 *
 * The Beam game development API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Beam.Client.FileParameter;
using OpenAPIDateConverter = Beam.Client.OpenAPIDateConverter;

namespace Beam.Model
{
    /// <summary>
    /// GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination
    /// </summary>
    [DataContract(Name = "GetAssetFilterOptionsBodyInput_responseOptions_inner_pagination")]
    public partial class GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination : IEquatable<GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination" /> class.
        /// </summary>
        /// <param name="limit">limit (required).</param>
        /// <param name="nextPageKey">nextPageKey (required).</param>
        public GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination(decimal limit = default(decimal), string nextPageKey = default(string))
        {
            this.Limit = limit;
            // to ensure "nextPageKey" is required (not null)
            if (nextPageKey == null)
            {
                throw new ArgumentNullException("nextPageKey is a required property for GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination and cannot be null");
            }
            this.NextPageKey = nextPageKey;
        }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Gets or Sets NextPageKey
        /// </summary>
        [DataMember(Name = "nextPageKey", IsRequired = true, EmitDefaultValue = true)]
        public string NextPageKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination {\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  NextPageKey: ").Append(NextPageKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination);
        }

        /// <summary>
        /// Returns true if GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination instances are equal
        /// </summary>
        /// <param name="input">Instance of GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetAssetFilterOptionsBodyInputResponseOptionsInnerPagination input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Limit == input.Limit ||
                    this.Limit.Equals(input.Limit)
                ) && 
                (
                    this.NextPageKey == input.NextPageKey ||
                    (this.NextPageKey != null &&
                    this.NextPageKey.Equals(input.NextPageKey))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Limit.GetHashCode();
                if (this.NextPageKey != null)
                {
                    hashCode = (hashCode * 59) + this.NextPageKey.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
